### ISSUE TITLE
Won't compile on rust 1.55?

### ISSUE THREAD

**Issue by blipmusic** [AdrianEddy/telemetry-parser#2]
I get the following error on rust 1.55 (mac OS 11.6, M1):

```
error[E0599]: no variant or associated item named `Vec_String` found for enum `tags_impl::TagValue` in the current scope
   --> src/gopro/klv.rs:71:40
    |
71  |                           _ => TagValue::Vec_String(ValueType::new(|d| Self::parse_strings(d), |v| format!("{:?}", v), tag_data.to_vec())),
    |                                          ^^^^^^^^^^ variant or associated item not found in `tags_impl::TagValue`
...
85  | /         types! {
86  | |             b'b' => (i8,  |d| d.read_i8()),
87  | |             b'B' => (u8,  |d| d.read_u8()),
88  | |             b's' => (i16, |d| d.read_i16::<BigEndian>()),
...   |
97  | |             b'Q' => (f64, |d| Ok(d.read_i32::<BigEndian>()? as f64 + (d.read_u32::<BigEndian>()? as f64 / 4294967295.0))),
98  | |         }
    | |_________- in this macro invocation
    |
   ::: src/tags_impl.rs:103:9
    |
103 |           pub enum TagValue {
    |           ----------------- variant or associated item `Vec_String` not found here
    |
    = note: this error originates in the macro `types` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Haven't dabbled with macros yet, but is it that this variant is not generated somehow?

**Comment by AdrianEddy** [comment]
I missed some files when pushing the changes, fixed now
